name: Hello World

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-22.04

    steps:
      - name: Print Hello World
        run: echo "Hello World!"

      - name: Now it is
        run: date

      - name: Directory Content
        run: ls -l
